### ISSUE TITLE
Saves class doesn,t distinguish levels runs well if they have all the othe infos identical

### ISSUE THREAD

**Issue by shenef** [GB127/SRC-statistics#80]
similar to #78 
```     Fetching The Adventures of Cookie & Cream - Any% (Co-op)
Prepping the Runs table...
Prepping the Saves table...
Initializing Saves
Traceback (most recent call last):
  File "C:\...\SRC-statistics-master\main.py", line 7, in <module>
    user = user(input("Who? "))
  File "C:\...\SRC-statistics-master\user.py", line 23, in __init__
    self.Saves = Saves(self.PBs, self.Runs)
  File "C:\...\SRC-statistics-master\Saves.py", line 14, in __init__
    tempo = Save(pb, Runs)
  File "C:\...\SRC-statistics-master\Saves.py", line 74, in __init__
    self.runs.sort()
  File "C:\...\SRC-statistics-master\generic.py", line 159, in __lt__
    raise BaseException(f'\n{self}\n{other}\n{list(self.__dict__.keys())}')
BaseException:
  PC   | Inertia                        | 200FPS (Default)     |   0:00:06
  PC   | Inertia                        | 200FPS (Default)     |   0:00:06
['IDs', 'system', 'game', 'category', 'level', 'time']
```

![image](https://user-images.githubusercontent.com/20268890/127480175-94e4dca6-90fd-433b-bd03-a1b6f729efed.png)

**Comment by GB127** [comment]
In the code, internally it is not truncated. But the display is truncated. I had to do a lot of shenaginans in order to be able to calculate seconds and still display the time in a beautiful way. And I chose to truncate milliseconds to save some headaches.


This is the same error from the other issue. I wonder if you forgot to download the last commit?

**Comment by GB127** [comment]
![image](https://user-images.githubusercontent.com/62620901/127510862-71985251-28fe-4578-9af0-5f641cf936da.png)


As we can see here, it is sorted correctly.

**Comment by GB127** [comment]
This screen is from the super mario bros. leaderboard

**Comment by shenef** [comment]
> This is the same error from the other issue. I wonder if you forgot to download the last commit?
I'm certain i'm on the latest code, downloaded the repo on another PC, ran it and got the same error (took a few tries because of "service is too busy").

**Comment by GB127** [comment]
I will look into it this weekend. Is xdrhellx a user with much less runs than nordanix?

**Comment by GB127** [comment]
Okay I understand the issue here. The issue is not because the seconds are truncated, as they are kept internally. The issue is the same as #78. It's because my Saves section doesn't have something for these levels names and all.

As mentionned in #81 , I made a tempo fix to allow you to still use the table.

**Comment by GB127** [comment]
@shenef  : This commit should fix this. (But download the commit after because it get rids of the tempo fix.
